apiVersion: v1
metadata:
  name: metrics-app-postgres
spec:
  ports:
    - name: port-1
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: port-2
      protocol: TCP
      port: 9779
      targetPort: 9779
    - name: port-3
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    app: metrics-app-postgres
    group: metrics-app
    provider: jkube
status:

